[project]
name = "quote-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Roldán Real Gómez", email = "roldanrealg@gmail.com" }
]
requires-python = ">=3.12.12"
dependencies = []

[project.scripts]
quote-generator = "quote_generator:main"

[build-system]
requires = ["uv_build>=0.12.20,<0.13.0"]
build-backend = "uv_build"
