[project]
name = "quote-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Roldán Real Gómez", email = "roldanrealg@gmail.com" }
]
requires-python = ">=3.12.12"
dependencies = []

[project.scripts]
quote-generator = "quote_generator:main"

[build-system]
requires = ["uv_build>=0.12.20,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "bandit>=1.9.4",
    "black>=26.5.1",
    "flake8>=7.4.1",
    "isort>=9.0.2",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "safety>=3.8.1",
]
docs = [
  "sphinx>=9.1.0"
]
